spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/taskflowdb}
    username: ${DB_USERNAME:taskflow_user}
    password: ${DB_PASSWORD:taskflow123}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true


  #UNCOMMENT WHEN FIRST UPDATE, COMMENT WHEN CREATE
#sql:
#  init:
#    mode: always
#    data-locations:
#      - classpath:data/roles.sql
#      - classpath:data/task_priorities.sql
#      - classpath:data/task_statuses.sql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
